### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by rfgarnier** [AKouki/SignalR-Chat#11]
can i run the update-database also in a way it creates the database in a SQL Server instead of the SQL EXpress

**Comment by AKouki** [comment]
Please,

- First, change the ConnectionString in appsettings.json with the SQL connection string you want to use
- Run update-database

**Comment by rfgarnier** [comment]
This works, thank you

**Comment by rfgarnier** [comment]
When I publish the project it does not publish all content like identity/account is that with a reason?

**Comment by AKouki** [comment]
What do you mean it does not publish all content? are you refering to the database?
Can you give me please more details.

**Comment by rfgarnier** [comment]
Previous message was my fault, missing .net core.
