### ISSUE TITLE
update

### ISSUE THREAD

**Issue by rfgarnier** [AKouki/SignalR-Chat#12]
Hallo, 

I hope you can help me out with the following. 
I changed the code so we can change the roomnames afterwards. 
It works and we also post back a procedure with signalr to update all users with the new info. 

But I do not get it working to update the content at the clients without refreshing the page. 

I tried this 
var temp;
            ko.utils.arrayForEach(self.TweetDeckRooms(), function (room) {
                if (room.id() == id)
                    temp = room;
            });
            temp.Name = Name;

and this:

var recordToupdate = this.TweetDeckRooms.FirstOrDefault(x => x.TweetDeckRoom.id == id);
if (recordToupdate != null) {
               recordToupdate.Name = room.Name;
            
           }

But both do not work

**Comment by AKouki** [comment]
Please check the last update.

You can now edit the room name.

**Comment by rfgarnier** [comment]
> Please check the last update/commit.
> 
> You can now edit the room name.

Thank you , really appreciate you fast response.

**Comment by rfgarnier** [comment]
Hallo Albion,

In chat.js   after a change of the roomname you give a  self.joinRoom(item);  
this means everyone is redirected to that room in the chat, is there a workaround to not do that and only update the content.

**Comment by AKouki** [comment]
Hello,

thank you for your feedback. There is a small bug im going to fix right now.

Currently everyone is getting the updated room details so they can update their list. The bug is that, also everyone is re-joining the updated room. Only users in this room should rejoin.

**Comment by rfgarnier** [comment]
i left this out, && r.Admin.UserName == User.Identity.Name  I assume you did this to only allow the creator to change the name?

**Comment by AKouki** [comment]
You can edit/delete only your own rooms.

**Comment by rfgarnier** [comment]
The identity system allows also to use the forgot password functionality, where can I find any documentation how to configure this. There is no code in the application but it will show the options when you call the /Identity/Account/ForgotPassword  url.
Is there a way to change this code and how do you add the SMTP server details for this.

**Comment by rfgarnier** [comment]
I was wondering can I reach you by email, we have a different project which maybe you can be interested developing the basis for us?

**Comment by AKouki** [comment]
Search "Scaffold Identity"

Everything about identity is under Areas/Identity.
You can override the default behaviour/layout: Right Click on project - Add - New Scaffolded Item - Identity - Identity and select the component you want to override.
