### ISSUE TITLE
Private messages not saved

### ISSUE THREAD

**Issue by senadburak** [AKouki/SignalR-Chat#15]
Hi,

I'm not sure if this is by design but private messages are not saved to database.

Why is so?

**Comment by AKouki** [comment]
Hello,

This is by design as it concept was more about messaging in groups/rooms.

It is in my plans to fully support the private messages. I can't provide any date about when im going to do it.

**Comment by senadburak** [comment]
Can't wait to see the new functionality. I think I am not the only one who need to see full support for private messaging.
This will extend the current project, whis is by the way already very good.

Cheers

**Comment by AKouki** [comment]
I am also thinking to re-write this using React...

**Comment by meistvan** [comment]
Please do it!!

Sent from my iPhone

On Jul 6, 2021, at 07:13, Albion Kouki ***@***.***> wrote:

﻿

I am also thinking to re-write this using React...

**Comment by senadburak** [comment]
One small suggestion, ie. improvement.
In index.cshtml on line 65 if you change  <div class="left-side"> to

<div class="left-side" **data-bind="if: !$data.isMine()**">

then the sender's avatar won't be shown on his form, while others will still see it. It is really not needed for sender to see his own avatars all the time.

In this way you save the space, which is always a good thing.

Rgds. Senad

**Comment by liuliucn** [comment]
@AKouki Great demo! Could you help me understand when to use the 'Create' method in MessagesController versus the 'SendPrivate' method in ChatHub? What are the design considerations for choosing between these two approaches?
