### ISSUE TITLE
One small suggestion, ie. improvement.

### ISSUE THREAD

**Issue by senadburak** [AKouki/SignalR-Chat#16]
In index.cshtml on line 62 if you change  `<div class="left-side">` to

`<div class="left-side" data-bind="if: !$data.isMine()">`

then the sender's avatar won't be shown on his form, while others will still see it. It is really not needed for sender to see his own avatars all the time.

In this way you save the space, which is always a good thing. It also looks better in my opinion.

Rgds. Senad

**Comment by AKouki** [comment]
Hello,
thank you for the suggestion, however i believe this is something subjective and for the moment i think it's okay showing your own avatar.
This is more an "guide" project. You can fork it and change the layout to meet your criteria.
