### ISSUE TITLE
delete message

### ISSUE THREAD

**Issue by feryt20** [AKouki/SignalR-Chat#21]
hi
delete message is not developed
and image messages vanished after refreshing page

**Comment by AKouki** [comment]
Hi,
the delete message is coming with next update, propably tommorow.

Image messages are working fine to me. Can you give more details?

**Comment by feryt20** [comment]
Thank you
Image messages works but I mean it doesn’t save to database 
It just show the picture once and after refreshing page it disappears

**Comment by AKouki** [comment]
The image is uploaded to wwwroot/uploads folder and a reference is stored in database. It is working for me.

Maby you talk about the live demo where the image upload functionality is disabled for security reasons?

**Comment by AKouki** [comment]
The message delete feature has been implemented.

If you still have problem i recommend you:
- Fork the last project
- Clear site data (Open browser console - Application - Clear site data)
- Delete the old database (if possible)
- Delete all bin/obj folders and rebuild the app
- Follow **Getting Started** section to rebuild the database
