### ISSUE TITLE
Problems with Getting Started

### ISSUE THREAD

**Issue by francamacdowell** [AKouki/SignalR-Chat#3]
Hi! ;)

I've got some problems with the last command of  **Getting Started** session. When I run `update-database` the return is:

> Directory lookup for the file "C:\Users\franc\Workspace\SignalR-Chat-master\Chat.Web\App_Data\aspnet-Chat.Web-20170315074639.mdf" failed with the operating system error 2(O sistema não pode encontrar o arquivo especificado.).

Can you help me?

**Comment by AKouki** [comment]
Hello,

Navigate to your source SignalR-Chat-master\Chat.Web\ and create folder with name App_Data.

**Comment by francamacdowell** [comment]
Hey,

It works, thanks a lot!

I'm learning so much with you project ;)
