### ISSUE TITLE
New User bug

### ISSUE THREAD

**Issue by Vinod1144** [AKouki/SignalR-Chat#9]
Hi,

I am login with two different user from two browser, both can chat easily,
but at the same time i am gonna register with the 3rd account and then login at that time 3rd user name doesn't come up with the existing logins for existing login I need to hit the F5 button or reload the page then it should work.

can you please check and do the necessary changes in master branch?

Thanks.

**Comment by Vinod1144** [comment]
It is even the same when i login with one person and in incognito mode i login with different person then in 1st login i didn't see the name of 2nd person who login.

Thanks.

**Comment by AKouki** [comment]
Hello, i tried to simulate your problem and i used 3 browsers (Chrome, Edge, and Firefox). I also tried to register/login with 3rd account in icognito mode and i didn't have any problem.

If this happens only in feature/dm (now deleted) branch, and in private chat window, sorry i can't provide any solution for it as it was an unofficial-fast solution.

If youre using an older version, please:
- Re-create the database
- Delete cookies from your browsers

**Comment by Vinod1144** [comment]
I'm trying with latest code and everything recreated and delete cookies but still issue is their,

can you show me the code where other **Online users** are get to know the new user is arrived and you were adding them into the **existing online users**?

**Comment by AKouki** [comment]
Everything is in ChatHub.cs

When an user moves room (or signout) it sends message to the other users in same group to remove this user.
await Clients.OthersInGroup(user.CurrentRoom).SendAsync("removeUser", user);

Currently you can have one user only in one room. It does not support multiple rooms.
